namespace BGCS
{
    /// <summary>
    /// Defines the public class <c>CsCodeGeneratorConfig</c>.
    /// </summary>
    public partial class CsCodeGeneratorConfig
    {
        /// <summary>
        /// Gets <c>Default</c>.
        /// </summary>
        public static CsCodeGeneratorConfig Default => new CsCodeGeneratorConfig()
        {
            TypeMappings = new()
            {
                {"uint8_t", "byte"},
                {"uint16_t", "ushort"},
                {"uint32_t", "uint"},
                {"uint64_t", "ulong"},
                {"int8_t", "sbyte"},
                {"int32_t", "int"},
                {"int16_t", "short"},
                {"int64_t", "long"},
                {"int64_t*", "long*"},
                {"unsigned char", "byte"},
                {"signed char", "sbyte"},
                {"char", "byte"},
                {"size_t", "nuint"},
                {"bool", "int"},
            },
            Keywords = new()
            {
                "abstract",
                "as",
                "base",
                "bool",
                "break",
                "byte",
                "case",
                "catch",
                "char",
                "checked",
                "class",
                "const",
                "continue",
                "decimal",
                "default",
                "delegate",
                "do",
                "double",
                "else",
                "enum",
                "event",
                "explicit",
                "extern",
                "false",
                "finally",
                "fixed",
                "float",
                "for",
                "foreach",
                "goto",
                "if",
                "implicit",
                "in",
                "int",
                "interface",
                "internal",
                "is",
                "lock",
                "long",
                "namespace",
                "new",
                "null",
                "object",
                "operator",
                "out",
                "override",
                "params",
                "private",
                "protected",
                "public",
                "readonly",
                "ref",
                "return",
                "sbyte",
                "sealed",
                "short",
                "sizeof",
                "stackalloc",
                "static",
                "string",
                "struct",
                "switch",
                "this",
                "throw",
                "true",
                "try",
                "typeof",
                "uint",
                "ulong",
                "unchecked",
                "unsafe",
                "ushort",
                "using",
                "using static",
                "virtual",
                "void",
                "volatile",
                "while",
                "yield"
            },
            VaryingTypes = ["ReadOnlySpan<byte>", "string", "ref string"]
        };
    }
}
