using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.Loader;
using System.Threading.Tasks;
using BGCS.Core.Logging;
using BGCS.CppAst.Parsing;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Emit;
using Xunit;

namespace BGCS.Tests;

public class GeneratedCodeCompilationMatrixTests
{
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate int NativeIntCallback(int value);
    [Fact]
    public void Generate_Matrix_OutputShouldCompileAndExposeExpectedSemantics()
    {
        foreach (var scenario in CreateScenarios())
        {
            var run = RunGenerator(scenario);
            try
            {
                AssertGeneratorSucceeded(scenario.Name, run.Ok, run.Messages);

                if (scenario.ExpectSingleFileOutput)
                {
                    string[] files = Directory.GetFiles(run.OutputPath, "*.cs", SearchOption.AllDirectories);
                    Assert.Single(files);

                    string merged = File.ReadAllText(files[0]);
                    Assert.Contains("partial struct", merged, StringComparison.Ordinal);
                    Assert.Contains("Native", merged, StringComparison.Ordinal);
                    Assert.Equal(1, CountAutoGeneratedCommentBlocks(merged));
                }

                Assembly asm = CompileGeneratedSources(run.OutputPath, "BGCS.Generated.Matrix." + scenario.Name);

                for (int i = 0; i < scenario.ExpectedTypeNames.Count; i++)
                {
                    Assert.NotNull(asm.GetType($"{scenario.Namespace}.{scenario.ExpectedTypeNames[i]}"));
                }

                for (int i = 0; i < scenario.ExpectedMethodNames.Count; i++)
                {
                    MethodInfo? method = FindMethodByName(asm, scenario.ExpectedMethodNames[i]);
                    Assert.NotNull(method);
                }

                scenario.VerifyAssembly?.Invoke(asm, run);
            }
            finally
            {
                Cleanup(run.TempDirectory);
            }
        }
    }

    [Fact]
    public void Generate_WhenParsingFails_ShouldPreserveLastSuccessfulOutput()
    {
        string temp = Path.Combine(Path.GetTempPath(), "bgcs-output-transaction-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        string headerPath = Path.Combine(temp, "input.h");
        string outputPath = Path.Combine(temp, "out");
        File.WriteAllText(headerPath, "int bgcs_valid(void);");
        CsCodeGeneratorConfig config = new()
        {
            ApiName = "TransactionApi",
            Namespace = "Transaction.Generated",
            LibName = "transaction",
            ImportType = ImportType.DllImport,
            GenerateExtensions = false,
            MergeGeneratedFilesToSingleFile = true
        };
        CsCodeGenerator generator = new(config);

        try
        {
            Assert.True(generator.Generate(headerPath, outputPath));
            string bindingsPath = Path.Combine(outputPath, "Bindings.cs");
            string lastGood = File.ReadAllText(bindingsPath);
            File.WriteAllText(headerPath, "int bgcs_invalid(");

            Assert.False(generator.Generate(headerPath, outputPath));
            Assert.Equal(lastGood, File.ReadAllText(bindingsPath));
        }
        finally
        {
            Cleanup(temp);
        }
    }

    [Fact]
    public void Generate_WindowsNativeAbi_ShouldMatchCompiledDllAtRuntime()
    {
        if (!OperatingSystem.IsWindows())
            return;
        string llvm = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles), "LLVM", "bin");
        string clang = Path.Combine(llvm, "clang.exe");
        string linker = Path.Combine(llvm, "lld-link.exe");
        if (!File.Exists(clang) || !File.Exists(linker))
            return;
        string temp = Path.Combine(Path.GetTempPath(), "bgcs-native-abi-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        const string libraryName = "bgcs_native_abi_test";
        string header = Path.Combine(temp, "abi.h");
        string source = Path.Combine(temp, "abi.c");
        string objectFile = Path.Combine(temp, "abi.obj");
        string dll = Path.Combine(AppContext.BaseDirectory, libraryName + ".dll");
        string output = Path.Combine(temp, "generated");
        File.WriteAllText(header,
            "#define API __declspec(dllimport)\ntypedef struct BgcsAbi { int x; double y; } BgcsAbi;\n#pragma pack(push,1)\ntypedef struct BgcsPacked { unsigned char tag; int value; } BgcsPacked;\n#pragma pack(pop)\ntypedef int (*BgcsIntCallback)(int value);\nAPI int bgcs_abi_size(void);\nAPI int bgcs_abi_y_offset(void);\nAPI int bgcs_packed_size(void);\nAPI int bgcs_packed_value_offset(void);\nAPI double bgcs_abi_sum(BgcsAbi value);\nAPI int bgcs_utf8_length(const char* text);\nAPI int bgcs_call_callback(BgcsIntCallback callback, int value);");
        File.WriteAllText(source,
            "#define API __declspec(dllexport)\nint _fltused=0;\ntypedef struct BgcsAbi { int x; double y; } BgcsAbi;\n#pragma pack(push,1)\ntypedef struct BgcsPacked { unsigned char tag; int value; } BgcsPacked;\n#pragma pack(pop)\ntypedef int (*BgcsIntCallback)(int value);\nAPI int bgcs_abi_size(void){return sizeof(BgcsAbi);}\nAPI int bgcs_abi_y_offset(void){return __builtin_offsetof(BgcsAbi,y);}\nAPI int bgcs_packed_size(void){return sizeof(BgcsPacked);}\nAPI int bgcs_packed_value_offset(void){return __builtin_offsetof(BgcsPacked,value);}\nAPI double bgcs_abi_sum(BgcsAbi value){return value.x+value.y;}\nAPI int bgcs_utf8_length(const char* text){int length=0;while(text[length])length++;return length;}\nAPI int bgcs_call_callback(BgcsIntCallback callback,int value){return callback(value);}");
        try
        {
            RunProcess(clang, temp, ["--target=x86_64-pc-windows-msvc", "-c", source, "-o", objectFile]);
            RunProcess(linker, temp, ["/dll", "/noentry", "/out:" + dll, objectFile]);
            CsCodeGeneratorConfig config = new()
            {
                Namespace = "BGCS.NativeAbi.Generated",
                ApiName = "NativeAbi",
                LibName = libraryName,
                ImportType = ImportType.DllImport,
                GenerateExtensions = false,
                MergeGeneratedFilesToSingleFile = true,
                ParserKind = CppParserKind.C
            };
            Assert.True(new CsCodeGenerator(config).Generate(header, output));
            Assembly assembly = CompileGeneratedSources(output, "BGCS.NativeAbi.Runtime");
            Type abiType = assembly.GetType("BGCS.NativeAbi.Generated.BgcsAbi")!;
            Type packedType = assembly.GetType("BGCS.NativeAbi.Generated.BgcsPacked")!;
            Type apiType = assembly.GetType("BGCS.NativeAbi.Generated.NativeAbi")!;
            string previousDirectory = Environment.CurrentDirectory;
            try
            {
                Environment.CurrentDirectory = temp;
                int nativeSize = (int)apiType.GetMethod("BgcsAbiSizeNative", BindingFlags.Static | BindingFlags.NonPublic)!.Invoke(null, null)!;
                int nativeOffset = (int)apiType.GetMethod("BgcsAbiYOffsetNative", BindingFlags.Static | BindingFlags.NonPublic)!.Invoke(null, null)!;
                Assert.Equal(nativeSize, Marshal.SizeOf(abiType));
                Assert.Equal(nativeOffset, Marshal.OffsetOf(abiType, "Y").ToInt32());
                int packedSize = (int)apiType.GetMethod("BgcsPackedSizeNative", BindingFlags.Static | BindingFlags.NonPublic)!.Invoke(null, null)!;
                int packedOffset = (int)apiType.GetMethod("BgcsPackedValueOffsetNative", BindingFlags.Static | BindingFlags.NonPublic)!.Invoke(null, null)!;
                Assert.Equal(packedSize, Marshal.SizeOf(packedType));
                Assert.Equal(packedOffset, Marshal.OffsetOf(packedType, "Value").ToInt32());
                object value = Activator.CreateInstance(abiType)!;
                abiType.GetField("X")!.SetValue(value, 4);
                abiType.GetField("Y")!.SetValue(value, 2.5);
                double sum = (double)apiType.GetMethod("BgcsAbiSumNative", BindingFlags.Static | BindingFlags.NonPublic)!.Invoke(null, [value])!;
                Assert.Equal(6.5, sum);
                MethodInfo utf8Length = Assert.Single(apiType.GetMethods(BindingFlags.Static | BindingFlags.Public), method =>
                    method.Name == "BgcsUtf8Length" && method.GetParameters() is [{ ParameterType: var parameterType }] && parameterType == typeof(string));
                Assert.Equal(6, (int)utf8Length.Invoke(null, ["你好"])!);
                NativeIntCallback callback = input => input * 3;
                nint callbackPointer = Marshal.GetFunctionPointerForDelegate(callback);
                MethodInfo callCallback = Assert.Single(apiType.GetMethods(BindingFlags.Static | BindingFlags.Public), method =>
                    method.Name == "BgcsCallCallback" && method.GetParameters() is [{ ParameterType: var first }, _] && first == typeof(nint));
                Assert.Equal(21, (int)callCallback.Invoke(null, [callbackPointer, 7])!);
                GC.KeepAlive(callback);
            }
            finally
            {
                Environment.CurrentDirectory = previousDirectory;
            }
        }
        finally
        {
            Cleanup(temp);
        }
    }

    private static void RunProcess(string executable, string workingDirectory, IReadOnlyList<string> arguments)
    {
        ProcessStartInfo start = new(executable)
        {
            WorkingDirectory = workingDirectory,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false
        };
        foreach (string argument in arguments)
            start.ArgumentList.Add(argument);
        using Process process = Process.Start(start)!;
        Task<string> stdout = process.StandardOutput.ReadToEndAsync();
        Task<string> stderr = process.StandardError.ReadToEndAsync();
        process.WaitForExit();
        Task.WaitAll(stdout, stderr);
        Assert.True(process.ExitCode == 0, stdout.Result + stderr.Result);
    }

    private static List<CompileScenario> CreateScenarios()
    {
        return
        [
            new()
            {
                Name = "C_Primitives_And_Struct",
                Header = """
                    typedef struct BgcsPoint
                    {
                        int x;
                        int y;
                    } BgcsPoint;

                    int bgcs_add(int a, int b);
                    void bgcs_update(BgcsPoint* p);
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsPoint"],
                ExpectedMethodNames = ["BgcsAddNative", "BgcsUpdateNative"]
            },
            new()
            {
                Name = "C_Enum_Macro_Callback",
                Header = """
                    #define BGCS_CONST_A 42
                    typedef enum BgcsMode
                    {
                        BGCS_MODE_A = 0,
                        BGCS_MODE_B = 1
                    } BgcsMode;

                    typedef void (*BgcsCallback)(int value);
                    void bgcs_set_mode(BgcsMode mode);
                    void bgcs_set_callback(BgcsCallback callback);
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsMode", "BgcsCallback"],
                ExpectedMethodNames = ["BgcsSetModeNative", "BgcsSetCallbackNative"]
            },
            new()
            {
                Name = "Cpp_Extern_C",
                Header = """
                    namespace Hidden
                    {
                        class IgnoredClass
                        {
                        public:
                            int value;
                        };
                    }

                    extern "C"
                    {
                        int bgcs_from_cpp(int a);
                    }
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = [],
                ExpectedMethodNames = ["BgcsFromCppNative"]
            },
            new()
            {
                Name = "FunctionTable_Mode",
                Header = """
                    int bgcs_ping(void);
                    int bgcs_add2(int a, int b);
                    """,
                ImportType = ImportType.FunctionTable,
                ExpectedTypeNames = ["CompileApi"],
                ExpectedMethodNames = ["BgcsPingNative", "BgcsAdd2Native", "InitApi", "FreeApi"]
                ,
                Configure = cfg =>
                {
                    cfg.UseCustomContext = true;
                }
            },
            new()
            {
                Name = "SingleFile_Merge",
                Header = """
                    typedef struct BgcsValue
                    {
                        int v;
                    } BgcsValue;
                    int bgcs_read(BgcsValue* value);
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsValue"],
                ExpectedMethodNames = ["BgcsReadNative"],
                ExpectSingleFileOutput = true,
                Configure = cfg =>
                {
                    cfg.MergeGeneratedFilesToSingleFile = true;
                    cfg.GenerateRuntimeSource = false;
                }
            },
            new()
            {
                Name = "C_Union_Fixed_Array",
                Header = """
                    typedef union BgcsPacket
                    {
                        int values[4];
                        double scalar;
                    } BgcsPacket;
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsPacket"],
                VerifyAssembly = (assembly, _) =>
                {
                    Type packet = assembly.GetType("Compile.Generated.BgcsPacket")!;
                    Assert.Equal(0, Marshal.OffsetOf(packet, "Values_0").ToInt32());
                    Assert.Equal(4, Marshal.OffsetOf(packet, "Values_1").ToInt32());
                    Assert.Equal(8, Marshal.OffsetOf(packet, "Values_2").ToInt32());
                    Assert.Equal(12, Marshal.OffsetOf(packet, "Values_3").ToInt32());
                    Assert.Equal(16, Marshal.SizeOf(packet));
                    Assert.Equal(typeof(Span<int>), packet.GetProperty("Values")?.PropertyType);
                }
            },
            new()
            {
                Name = "C_Multidimensional_Array",
                Header = """
                    typedef struct BgcsMatrix
                    {
                        int values[2][3];
                    } BgcsMatrix;
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsMatrix"],
                VerifyAssembly = (assembly, _) =>
                {
                    Type matrix = assembly.GetType("Compile.Generated.BgcsMatrix")!;
                    Assert.Equal(24, Marshal.SizeOf(matrix));
                    Assert.Equal(20, Marshal.OffsetOf(matrix, "Values_5").ToInt32());
                    Assert.Equal(typeof(Span<int>), matrix.GetProperty("Values")?.PropertyType);
                }
            },
            new()
            {
                Name = "C_Pointer_Typedef_Array",
                Header = """
                    typedef void* BgcsThread;
                    typedef struct BgcsThreadPool
                    {
                        BgcsThread threads[4];
                    } BgcsThreadPool;
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsThreadPool"],
                Configure = cfg => cfg.AutoSquashTypedef = false,
                VerifyAssembly = (assembly, _) =>
                {
                    Type pool = assembly.GetType("Compile.Generated.BgcsThreadPool")!;
                    Assert.Equal(IntPtr.Size * 4, Marshal.SizeOf(pool));
                    Assert.Equal(typeof(Span<nint>), pool.GetProperty("Threads")?.PropertyType);
                }
            },
            new()
            {
                Name = "C_Handle_Properties_With_Aliases_And_Nested_Array",
                Header = """
                    typedef unsigned int BgcsUInt;
                    typedef void BgcsOpaque;
                    typedef struct BgcsHolder
                    {
                        struct NestedValue
                        {
                            int value;
                        } items[2];
                        BgcsUInt* values;
                        BgcsOpaque* opaque;
                    } BgcsHolder;
                    void bgcs_use_holder(BgcsHolder* holder);
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsHolder", "BgcsHolderPtr"],
                Configure = cfg =>
                {
                    cfg.AutoSquashTypedef = false;
                    cfg.WrapPointersAsHandle = true;
                },
                VerifyAssembly = (assembly, _) =>
                {
                    Type holder = assembly.GetType("Compile.Generated.BgcsHolder")!;
                    Type holderPointer = assembly.GetType("Compile.Generated.BgcsHolderPtr")!;
                    Type nested = holder.GetNestedType("NestedValue")!;
                    Type opaque = assembly.GetType("Compile.Generated.BgcsOpaque")!;
                    Assert.Equal(typeof(uint).MakePointerType(), holderPointer.GetProperty("Values")?.PropertyType);
                    Assert.Equal(opaque.MakePointerType(), holderPointer.GetProperty("Opaque")?.PropertyType);
                    Assert.Equal(typeof(Span<>).MakeGenericType(nested), holderPointer.GetProperty("Items")?.PropertyType);
                }
            },
            new()
            {
                Name = "C_Handle_Properties_Wrap_Later_Declared_Pointers",
                Header = """
                    typedef struct BgcsTarget BgcsTarget;
                    typedef struct BgcsOwner
                    {
                        BgcsTarget* target;
                    } BgcsOwner;
                    struct BgcsTarget
                    {
                        int value;
                    };
                    void bgcs_use_owner(BgcsOwner* owner);
                    void bgcs_use_target(BgcsTarget* target);
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsOwner", "BgcsOwnerPtr", "BgcsTarget", "BgcsTargetPtr"],
                Configure = cfg => cfg.WrapPointersAsHandle = true,
                VerifyAssembly = (assembly, _) =>
                {
                    Type ownerPointer = assembly.GetType("Compile.Generated.BgcsOwnerPtr")!;
                    Type targetPointer = assembly.GetType("Compile.Generated.BgcsTargetPtr")!;
                    Assert.Equal(targetPointer.MakeByRefType(), ownerPointer.GetProperty("Target")?.PropertyType);
                }
            },
            new()
            {
                Name = "C_Opaque_Pointer_Typedef_Does_Not_Emit_Underlying_Handle",
                Header = """
                    typedef struct BgcsOpaqueState *BgcsHandle;
                    BgcsHandle bgcs_create_handle(void);
                    void bgcs_destroy_handle(BgcsHandle handle);
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsHandle"],
                ExpectedMethodNames = ["BgcsCreateHandleNative", "BgcsDestroyHandleNative"],
                Configure = cfg => cfg.WrapPointersAsHandle = true,
                VerifyAssembly = (assembly, _) =>
                {
                    Assert.Null(assembly.GetType("Compile.Generated.BgcsOpaqueStatePtr"));
                    Type handle = assembly.GetType("Compile.Generated.BgcsHandle")!;
                    Assert.Equal(typeof(nint), handle.GetProperty("Handle")?.PropertyType);
                }
            },
            new()
            {
                Name = "C_Handle_Properties_With_Named_Anonymous_Unions",
                Header = """
                    typedef struct BgcsPlatforms
                    {
                        union
                        {
                            int value;
                        } first;
                        union
                        {
                            float value;
                        } second;
                    } BgcsPlatforms;
                    void bgcs_use_platforms(BgcsPlatforms* platforms);
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsPlatforms", "BgcsPlatformsPtr"],
                Configure = cfg => cfg.WrapPointersAsHandle = true,
                VerifyAssembly = (assembly, _) =>
                {
                    Type platforms = assembly.GetType("Compile.Generated.BgcsPlatforms")!;
                    Type platformsPointer = assembly.GetType("Compile.Generated.BgcsPlatformsPtr")!;
                    Assert.Equal(platforms.GetNestedType("FirstAnonymous")!.MakeByRefType(), platformsPointer.GetProperty("First")?.PropertyType);
                    Assert.Equal(platforms.GetNestedType("SecondAnonymous")!.MakeByRefType(), platformsPointer.GetProperty("Second")?.PropertyType);
                }
            },
            new()
            {
                Name = "C_Integer_Alias_Enum_Convention",
                Header = """
                    typedef enum BgcsFlags_
                    {
                        BgcsFlags_None = 0,
                        BgcsFlags_Enabled = 1
                    } BgcsFlags_;
                    typedef int BgcsFlags;
                    typedef enum BgcsPrivate_
                    {
                        BgcsPrivate_FromOther = BgcsFlags_Enabled
                    } BgcsPrivate_;
                    void bgcs_use_flags(BgcsFlags flags);
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsFlags", "BgcsPrivate"],
                ExpectedMethodNames = ["BgcsUseFlagsNative"],
                Configure = cfg => cfg.AutoSquashTypedef = false
            },
            new()
            {
                Name = "C_Typed_Variadic",
                Header = "int bgcs_log(const char* format, ...);",
                ImportType = ImportType.DllImport,
                ExpectedMethodNames = ["BgcsLogIntsNative", "BgcsLogInts"],
                Configure = cfg => cfg.VariadicFunctionVariants["bgcs_log"] =
                [
                    new VariadicFunctionVariant
                    {
                        Suffix = "Ints",
                        ParameterTypes = ["int", "int"],
                        ParameterNames = ["first", "second"]
                    }
                ]
            },
            new()
            {
                Name = "C_Callback_Field_Constructor",
                Header = """
                    typedef void (*BgcsFieldCallback)(int value);
                    typedef struct BgcsCallbackTable
                    {
                        BgcsFieldCallback callback;
                    } BgcsCallbackTable;
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsCallbackTable"],
                Configure = cfg => cfg.DelegatesAsVoidPointer = true
            },
            new()
            {
                Name = "C_Unsquashed_Callback_Bool_And_Pointer",
                Header = """
                    typedef bool (*BgcsPredicate)(void* context, bool enabled);
                    typedef struct BgcsPredicateTable
                    {
                        BgcsPredicate predicate;
                    } BgcsPredicateTable;
                    void bgcs_set_predicate(BgcsPredicate predicate);
                    void bgcs_get_predicate(BgcsPredicate* predicate);
                    """,
                ImportType = ImportType.FunctionTable,
                ExpectedTypeNames = ["BgcsPredicate", "BgcsPredicateTable"],
                ExpectedMethodNames = ["BgcsSetPredicate", "BgcsGetPredicate"],
                Configure = cfg =>
                {
                    cfg.AutoSquashTypedef = false;
                    cfg.BoolType = BoolType.Byte;
                    cfg.DelegatesAsVoidPointer = false;
                },
                VerifyAssembly = (assembly, _) =>
                {
                    Type predicate = assembly.GetType("Compile.Generated.BgcsPredicate")!;
                    Assert.Equal(typeof(byte), predicate.GetMethod("Invoke")!.ReturnType);
                    Assert.Equal(typeof(byte), predicate.GetMethod("Invoke")!.GetParameters()[1].ParameterType);
                }
            },
            new()
            {
                Name = "C_Nested_Api_Types",
                Header = """
                    typedef struct BgcsValue { int value; } BgcsValue;
                    typedef enum BgcsMode { BGCS_MODE_NONE = 0, BGCS_MODE_FAST = 1 } BgcsMode;
                    typedef int (*BgcsTransform)(BgcsValue* value, BgcsMode mode);
                    int bgcs_apply(BgcsValue* value, BgcsMode mode, BgcsTransform transform);
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["CompileApi+BgcsValue", "CompileApi+BgcsMode", "CompileApi+BgcsTransform"],
                ExpectedMethodNames = ["BgcsApply"],
                Configure = cfg =>
                {
                    cfg.AutoSquashTypedef = false;
                    cfg.NestGeneratedTypesInApi = true;
                    cfg.DelegatesAsVoidPointer = false;
                }
            },
            new()
            {
                Name = "C_Sentinel_Value_Handle",
                Header = """
                    typedef struct BgcsResourceHandle { unsigned short index; } BgcsResourceHandle;
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsResourceHandle"],
                Configure = cfg =>
                {
                    cfg.MemberNamingConvention = NamingConvention.Unknown;
                    cfg.ClassMappings.Add(new BGCS.Core.Mapping.TypeMapping(
                        "BgcsResourceHandle",
                        "BgcsResourceHandle",
                        null)
                    {
                        Validity = new BGCS.Core.Mapping.StructValidityMapping(
                            "index",
                            "ushort.MaxValue",
                            "Valid")
                    });
                },
                VerifyAssembly = (assembly, _) =>
                {
                    Type handleType = assembly.GetType("Compile.Generated.BgcsResourceHandle")!;
                    PropertyInfo property = handleType.GetProperty("Valid")!;
                    object valid = Activator.CreateInstance(handleType)!;
                    handleType.GetField("index")!.SetValue(valid, (ushort)7);
                    Assert.True((bool)property.GetValue(valid)!);
                    object invalid = Activator.CreateInstance(handleType)!;
                    handleType.GetField("index")!.SetValue(invalid, ushort.MaxValue);
                    Assert.False((bool)property.GetValue(invalid)!);
                }
            },
            new()
            {
                Name = "Cpp_Signed_Bitfield_And_Bool_Array",
                Header = """
                    struct BgcsPackedState
                    {
                        signed int delta : 5;
                        bool states[3];
                    };
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsPackedState"],
                Configure = cfg => cfg.BoolType = BoolType.Byte,
                VerifyAssembly = (assembly, _) =>
                {
                    Type type = assembly.GetType("Compile.Generated.BgcsPackedState")!;
                    object value = Activator.CreateInstance(type)!;
                    type.GetField("RawBits0")!.SetValue(value, 0b1_1111);
                    Assert.Equal(-1, type.GetProperty("Delta")!.GetValue(value));
                }
            },
            new()
            {
                Name = "C_Callback_Fields_With_Reused_Names",
                Header = """
                    typedef struct BgcsReader
                    {
                        void (*on_data)(int value);
                    } BgcsReader;
                    typedef struct BgcsWriter
                    {
                        void (*on_data)(float value);
                    } BgcsWriter;
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsReader", "BgcsWriter", "OnData", "OnData1"],
                VerifyAssembly = (assembly, _) =>
                {
                    Type first = assembly.GetType("Compile.Generated.OnData")!;
                    Type second = assembly.GetType("Compile.Generated.OnData1")!;
                    Type[] parameterTypes =
                    [
                        first.GetMethod("Invoke")!.GetParameters()[0].ParameterType,
                        second.GetMethod("Invoke")!.GetParameters()[0].ParameterType
                    ];
                    Assert.Contains(typeof(int), parameterTypes);
                    Assert.Contains(typeof(float), parameterTypes);
                }
            },
            new()
            {
                Name = "C_Macro_Redefinition_Uses_Final_Value",
                Header = """
                    #define BGCS_VALUE 0
                    #undef BGCS_VALUE
                    #define BGCS_VALUE 42
                    """,
                ImportType = ImportType.DllImport,
                VerifyAssembly = (assembly, _) =>
                {
                    Type api = assembly.GetType("Compile.Generated.CompileApi")!;
                    Assert.Equal(42, api.GetField("BGCS_VALUE")!.GetRawConstantValue());
                }
            },
            new()
            {
                Name = "C_Incomplete_Record_Typedef_Callbacks",
                Header = """
                    struct BgcsEncoderS;
                    typedef struct BgcsEncoderS BgcsEncoder;
                    typedef BgcsEncoder* (*BgcsBeginCallback)(void);
                    typedef void (*BgcsEndCallback)(struct BgcsEncoderS* encoder);
                    BgcsEncoder* bgcs_encoder_begin(void);
                    void bgcs_encoder_end(struct BgcsEncoderS* encoder);
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsEncoder", "BgcsBeginCallback", "BgcsEndCallback"],
                ExpectedMethodNames = ["BgcsEncoderBeginNative", "BgcsEncoderEndNative"],
                Configure = cfg => cfg.AutoSquashTypedef = false,
                VerifyAssembly = (assembly, _) =>
                {
                    Type encoder = assembly.GetType("Compile.Generated.BgcsEncoder")!;
                    Type begin = assembly.GetType("Compile.Generated.BgcsBeginCallback")!;
                    Type end = assembly.GetType("Compile.Generated.BgcsEndCallback")!;
                    Assert.Equal(encoder, begin.GetMethod("Invoke")!.ReturnType.GetElementType());
                    Assert.Equal(encoder, end.GetMethod("Invoke")!.GetParameters()[0].ParameterType.GetElementType());
                }
            },
            new()
            {
                Name = "C_External_Record_Typedef_Layout",
                Header = """
                    #include "external_types.h"
                    typedef ExternalMutex BgcsMutex;
                    typedef struct BgcsState
                    {
                        unsigned char tag;
                        BgcsMutex mutex;
                    } BgcsState;
                    """,
                AdditionalHeaders =
                {
                    ["external_types.h"] = "typedef struct ExternalMutex { long long storage[5]; } ExternalMutex;"
                },
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsMutex", "BgcsState"],
                Configure = cfg => cfg.AutoSquashTypedef = false,
                VerifyAssembly = (assembly, _) =>
                {
                    Type mutex = assembly.GetType("Compile.Generated.BgcsMutex")!;
                    Type state = assembly.GetType("Compile.Generated.BgcsState")!;
                    Assert.Equal(40, Marshal.SizeOf(mutex));
                    Assert.Equal(8, Marshal.OffsetOf(state, "Mutex").ToInt32());
                    Assert.Equal(48, Marshal.SizeOf(state));
                }
            },
            new()
            {
                Name = "C_Flexible_Array",
                Header = """
                    typedef struct BgcsSamples
                    {
                        int count;
                        float values[];
                    } BgcsSamples;
                    void bgcs_consume_samples(BgcsSamples* samples);
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsSamples", "BgcsSamplesPtr"],
                ExpectedMethodNames = ["BgcsConsumeSamplesNative"],
                Configure = cfg => cfg.WrapPointersAsHandle = true,
                VerifyAssembly = (assembly, _) =>
                {
                    Type samples = assembly.GetType("Compile.Generated.BgcsSamples")!;
                    Type samplesPointer = assembly.GetType("Compile.Generated.BgcsSamplesPtr")!;
                    Assert.Equal(4, Marshal.SizeOf(samples));
                    Assert.Equal(4, samples.GetField("ValuesOffset")?.GetValue(null));
                    MethodInfo? values = samplesPointer.GetMethod("Values", [typeof(int)]);
                    Assert.Equal(typeof(Span<float>), values?.ReturnType);
                }
            },
            new()
            {
                Name = "C_Union_Bitfields",
                Header = """
                    typedef union BgcsBits
                    {
                        unsigned int flags : 3;
                        int signed_value : 3;
                    } BgcsBits;
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsBits"],
                VerifyAssembly = (assembly, _) =>
                {
                    Type bits = assembly.GetType("Compile.Generated.BgcsBits")!;
                    Assert.Equal(4, Marshal.SizeOf(bits));
                    Assert.Equal(0, Marshal.OffsetOf(bits, "RawBits0").ToInt32());
                    Assert.Equal(0, Marshal.OffsetOf(bits, "RawBits1").ToInt32());
                    object value = Activator.CreateInstance(bits)!;
                    PropertyInfo signedValue = bits.GetProperty("SignedValue")!;
                    signedValue.SetValue(value, -1);
                    Assert.Equal(-1, signedValue.GetValue(value));
                }
            }
        ];
    }

    private static MethodInfo? FindMethodByName(Assembly asm, string name)
    {
        return asm
            .GetTypes()
            .SelectMany(x => x.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance))
            .FirstOrDefault(x => string.Equals(x.Name, name, StringComparison.Ordinal));
    }

    private static Assembly CompileGeneratedSources(string outputPath, string assemblyName)
    {
        string[] sourceFiles = Directory.GetFiles(outputPath, "*.cs", SearchOption.AllDirectories);
        Assert.NotEmpty(sourceFiles);

        SyntaxTree[] trees = sourceFiles
            .Select(path => CSharpSyntaxTree.ParseText(File.ReadAllText(path), path: path))
            .ToArray();

        CSharpCompilation compilation = CSharpCompilation.Create(
            assemblyName,
            trees,
            GetMetadataReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, allowUnsafe: true));

        using MemoryStream pe = new();
        EmitResult emit = compilation.Emit(pe);

        if (!emit.Success)
        {
            string diagnostics = string.Join(
                Environment.NewLine,
                emit.Diagnostics
                    .Where(x => x.Severity == DiagnosticSeverity.Error)
                    .Select(x => x.ToString()));
            Assert.Fail("Generated code compilation failed:\n" + diagnostics);
        }

        pe.Position = 0;
        AssemblyLoadContext alc = new("BGCS.Generated.Matrix", isCollectible: true);
        return alc.LoadFromStream(pe);
    }

    private static IEnumerable<MetadataReference> GetMetadataReferences()
    {
        string? tpa = AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") as string;
        if (string.IsNullOrWhiteSpace(tpa))
        {
            throw new InvalidOperationException("Missing TRUSTED_PLATFORM_ASSEMBLIES.");
        }

        HashSet<string> paths = new(StringComparer.OrdinalIgnoreCase);
        foreach (string path in tpa.Split(Path.PathSeparator))
        {
            paths.Add(path);
        }

        paths.Add(typeof(CsCodeGenerator).Assembly.Location);
        paths.Add(typeof(CsCodeGeneratorConfig).Assembly.Location);
        paths.Add(typeof(BGCS.Runtime.FunctionTable).Assembly.Location);
        return paths.Select(static path => MetadataReference.CreateFromFile(path));
    }

    private static void AssertGeneratorSucceeded(string scenarioName, bool ok, IReadOnlyList<LogMessage> messages)
    {
        string diagnostics = string.Join(Environment.NewLine, messages.Select(message => message.ToString()));
        Assert.True(ok, $"Generation failed for scenario '{scenarioName}'.{Environment.NewLine}{diagnostics}");
        Assert.DoesNotContain(messages, x => x.Severtiy is LogSeverity.Error or LogSeverity.Critical);
    }

    private static RunResult RunGenerator(CompileScenario scenario)
    {
        string temp = Path.Combine(Path.GetTempPath(), "bgcs-compile-matrix-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);

        string headerPath = Path.Combine(temp, "input.h");
        string outputPath = Path.Combine(temp, "out");
        File.WriteAllText(headerPath, scenario.Header);
        foreach ((string fileName, string contents) in scenario.AdditionalHeaders)
            File.WriteAllText(Path.Combine(temp, fileName), contents);

        CsCodeGeneratorConfig cfg = new()
        {
            ApiName = "CompileApi",
            Namespace = scenario.Namespace,
            LibName = "compiletest",
            GenerateExtensions = false,
            ImportType = scenario.ImportType,
            DelegatesAsVoidPointer = false
        };
        scenario.Configure?.Invoke(cfg);

        CppParserOptions parserOptions = new()
        {
            ParseMacros = true,
            ParseComments = true,
            ParseSystemIncludes = false,
            ParseCommentAttribute = true,
            ParserKind = CppParserKind.Cpp,
            AutoSquashTypedef = false
        };
        parserOptions.AdditionalArguments.Add("-undef");

        CsCodeGenerator gen = new(cfg);
        bool ok = gen.Generate(parserOptions, headerPath, outputPath);
        return new(ok, temp, outputPath, gen.Messages);
    }

    private static void Cleanup(string directory)
    {
        if (Directory.Exists(directory))
        {
            Directory.Delete(directory, true);
        }
    }

    private static int CountAutoGeneratedCommentBlocks(string text)
    {
        const string marker = "<auto-generated>";
        int count = 0;
        int index = 0;
        while (index < text.Length)
        {
            int found = text.IndexOf(marker, index, StringComparison.Ordinal);
            if (found == -1)
            {
                break;
            }

            count++;
            index = found + marker.Length;
        }

        return count;
    }

    private sealed class CompileScenario
    {
        public string Name { get; set; } = string.Empty;

        public string Header { get; set; } = string.Empty;

        public string Namespace { get; set; } = "Compile.Generated";

        public ImportType ImportType { get; set; } = ImportType.DllImport;

        public bool ExpectSingleFileOutput { get; set; }

        public Action<CsCodeGeneratorConfig>? Configure { get; set; }

        public Action<Assembly, RunResult>? VerifyAssembly { get; set; }

        public Dictionary<string, string> AdditionalHeaders { get; set; } = [];

        public List<string> ExpectedTypeNames { get; set; } = [];

        public List<string> ExpectedMethodNames { get; set; } = [];
    }

    private sealed record RunResult(
        bool Ok,
        string TempDirectory,
        string OutputPath,
        IReadOnlyList<LogMessage> Messages);
}
