<Project>
  <PropertyGroup Label="Release">
    <Version>2.1.0</Version>
  </PropertyGroup>

  <PropertyGroup Label="Compilation">
    <LangVersion>13.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)/obj/**;$(MSBuildProjectDirectory)/bin/**</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup Label="Public API documentation">
    <GenerateDocumentationFile Condition="$([System.String]::Copy('$(MSBuildProjectDirectory)').StartsWith('$(MSBuildThisFileDirectory)src'))">true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1572;CS1573;CS1591</WarningsAsErrors>
  </PropertyGroup>
</Project>
