using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;
using BGCS.Core.Logging;
using BGCS.CppAst.Parsing;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Emit;
using Xunit;

namespace BGCS.Tests;

public class GeneratedCodeCompilationMatrixTests
{
    [Fact]
    public void Generate_Matrix_OutputShouldCompileAndExposeExpectedSemantics()
    {
        foreach (var scenario in CreateScenarios())
        {
            var run = RunGenerator(scenario);
            try
            {
                AssertGeneratorSucceeded(scenario.Name, run.Ok, run.Messages);

                if (scenario.ExpectSingleFileOutput)
                {
                    string[] files = Directory.GetFiles(run.OutputPath, "*.cs", SearchOption.AllDirectories);
                    Assert.Single(files);

                    string merged = File.ReadAllText(files[0]);
                    Assert.Contains("partial struct", merged, StringComparison.Ordinal);
                    Assert.Contains("Native", merged, StringComparison.Ordinal);
                    Assert.Equal(1, CountAutoGeneratedCommentBlocks(merged));
                }

                Assembly asm = CompileGeneratedSources(run.OutputPath, "BGCS.Generated.Matrix." + scenario.Name);

                for (int i = 0; i < scenario.ExpectedTypeNames.Count; i++)
                {
                    Assert.NotNull(asm.GetType($"{scenario.Namespace}.{scenario.ExpectedTypeNames[i]}"));
                }

                for (int i = 0; i < scenario.ExpectedMethodNames.Count; i++)
                {
                    MethodInfo? method = FindMethodByName(asm, scenario.ExpectedMethodNames[i]);
                    Assert.NotNull(method);
                }

                scenario.VerifyAssembly?.Invoke(asm, run);
            }
            finally
            {
                Cleanup(run.TempDirectory);
            }
        }
    }

    private static List<CompileScenario> CreateScenarios()
    {
        return
        [
            new()
            {
                Name = "C_Primitives_And_Struct",
                Header = """
                    typedef struct BgcsPoint
                    {
                        int x;
                        int y;
                    } BgcsPoint;

                    int bgcs_add(int a, int b);
                    void bgcs_update(BgcsPoint* p);
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsPoint"],
                ExpectedMethodNames = ["BgcsAddNative", "BgcsUpdateNative"]
            },
            new()
            {
                Name = "C_Enum_Macro_Callback",
                Header = """
                    #define BGCS_CONST_A 42
                    typedef enum BgcsMode
                    {
                        BGCS_MODE_A = 0,
                        BGCS_MODE_B = 1
                    } BgcsMode;

                    typedef void (*BgcsCallback)(int value);
                    void bgcs_set_mode(BgcsMode mode);
                    void bgcs_set_callback(BgcsCallback callback);
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsMode", "BgcsCallback"],
                ExpectedMethodNames = ["BgcsSetModeNative", "BgcsSetCallbackNative"]
            },
            new()
            {
                Name = "Cpp_Extern_C",
                Header = """
                    namespace Hidden
                    {
                        class IgnoredClass
                        {
                        public:
                            int value;
                        };
                    }

                    extern "C"
                    {
                        int bgcs_from_cpp(int a);
                    }
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = [],
                ExpectedMethodNames = ["BgcsFromCppNative"]
            },
            new()
            {
                Name = "FunctionTable_Mode",
                Header = """
                    int bgcs_ping(void);
                    int bgcs_add2(int a, int b);
                    """,
                ImportType = ImportType.FunctionTable,
                ExpectedTypeNames = ["CompileApi"],
                ExpectedMethodNames = ["BgcsPingNative", "BgcsAdd2Native", "InitApi", "FreeApi"]
                ,
                Configure = cfg =>
                {
                    cfg.UseCustomContext = true;
                }
            },
            new()
            {
                Name = "SingleFile_Merge",
                Header = """
                    typedef struct BgcsValue
                    {
                        int v;
                    } BgcsValue;
                    int bgcs_read(BgcsValue* value);
                    """,
                ImportType = ImportType.DllImport,
                ExpectedTypeNames = ["BgcsValue"],
                ExpectedMethodNames = ["BgcsReadNative"],
                ExpectSingleFileOutput = true,
                Configure = cfg =>
                {
                    cfg.MergeGeneratedFilesToSingleFile = true;
                    cfg.DeleteSplitFilesAfterMerging = true;
                    cfg.SingleFileOutputName = "Bindings.cs";
                }
            }
        ];
    }

    private static MethodInfo? FindMethodByName(Assembly asm, string name)
    {
        return asm
            .GetTypes()
            .SelectMany(x => x.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance))
            .FirstOrDefault(x => string.Equals(x.Name, name, StringComparison.Ordinal));
    }

    private static Assembly CompileGeneratedSources(string outputPath, string assemblyName)
    {
        string[] sourceFiles = Directory.GetFiles(outputPath, "*.cs", SearchOption.AllDirectories);
        Assert.NotEmpty(sourceFiles);

        SyntaxTree[] trees = sourceFiles
            .Select(path => CSharpSyntaxTree.ParseText(File.ReadAllText(path), path: path))
            .ToArray();

        CSharpCompilation compilation = CSharpCompilation.Create(
            assemblyName,
            trees,
            GetMetadataReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, allowUnsafe: true));

        using MemoryStream pe = new();
        EmitResult emit = compilation.Emit(pe);

        if (!emit.Success)
        {
            string diagnostics = string.Join(
                Environment.NewLine,
                emit.Diagnostics
                    .Where(x => x.Severity == DiagnosticSeverity.Error)
                    .Select(x => x.ToString()));
            Assert.True(false, "Generated code compilation failed:\n" + diagnostics);
        }

        pe.Position = 0;
        AssemblyLoadContext alc = new("BGCS.Generated.Matrix", isCollectible: true);
        return alc.LoadFromStream(pe);
    }

    private static IEnumerable<MetadataReference> GetMetadataReferences()
    {
        string? tpa = AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") as string;
        if (string.IsNullOrWhiteSpace(tpa))
        {
            throw new InvalidOperationException("Missing TRUSTED_PLATFORM_ASSEMBLIES.");
        }

        HashSet<string> paths = new(StringComparer.OrdinalIgnoreCase);
        foreach (string path in tpa.Split(Path.PathSeparator))
        {
            paths.Add(path);
        }

        paths.Add(typeof(CsCodeGenerator).Assembly.Location);
        paths.Add(typeof(CsCodeGeneratorConfig).Assembly.Location);
        paths.Add(typeof(BGCS.Runtime.FunctionTable).Assembly.Location);
        return paths.Select(static path => MetadataReference.CreateFromFile(path));
    }

    private static void AssertGeneratorSucceeded(string scenarioName, bool ok, IReadOnlyList<LogMessage> messages)
    {
        Assert.True(ok);
        Assert.DoesNotContain(messages, x => x.Severtiy is LogSeverity.Error or LogSeverity.Critical);
    }

    private static RunResult RunGenerator(CompileScenario scenario)
    {
        string temp = Path.Combine(Path.GetTempPath(), "bgcs-compile-matrix-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);

        string headerPath = Path.Combine(temp, "input.h");
        string outputPath = Path.Combine(temp, "out");
        File.WriteAllText(headerPath, scenario.Header);

        CsCodeGeneratorConfig cfg = new()
        {
            ApiName = "CompileApi",
            Namespace = scenario.Namespace,
            LibName = "compiletest",
            GenerateExtensions = false,
            ImportType = scenario.ImportType,
            DelegatesAsVoidPointer = false
        };
        scenario.Configure?.Invoke(cfg);

        CppParserOptions parserOptions = new()
        {
            ParseMacros = true,
            ParseComments = true,
            ParseSystemIncludes = false,
            ParseCommentAttribute = true,
            ParserKind = CppParserKind.Cpp,
            AutoSquashTypedef = false
        };
        parserOptions.AdditionalArguments.Add("-undef");

        CsCodeGenerator gen = new(cfg);
        bool ok = gen.Generate(parserOptions, headerPath, outputPath);
        return new(ok, temp, outputPath, gen.Messages);
    }

    private static void Cleanup(string directory)
    {
        if (Directory.Exists(directory))
        {
            Directory.Delete(directory, true);
        }
    }

    private static int CountAutoGeneratedCommentBlocks(string text)
    {
        const string marker = "<auto-generated>";
        int count = 0;
        int index = 0;
        while (index < text.Length)
        {
            int found = text.IndexOf(marker, index, StringComparison.Ordinal);
            if (found == -1)
            {
                break;
            }

            count++;
            index = found + marker.Length;
        }

        return count;
    }

    private sealed class CompileScenario
    {
        public string Name { get; set; } = string.Empty;

        public string Header { get; set; } = string.Empty;

        public string Namespace { get; set; } = "Compile.Generated";

        public ImportType ImportType { get; set; } = ImportType.DllImport;

        public bool ExpectSingleFileOutput { get; set; }

        public Action<CsCodeGeneratorConfig>? Configure { get; set; }

        public Action<Assembly, RunResult>? VerifyAssembly { get; set; }

        public List<string> ExpectedTypeNames { get; set; } = [];

        public List<string> ExpectedMethodNames { get; set; } = [];
    }

    private sealed record RunResult(
        bool Ok,
        string TempDirectory,
        string OutputPath,
        IReadOnlyList<LogMessage> Messages);
}
