<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Compilation">
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup Label="Project dependencies">
    <ProjectReference Include="../../../src/BGCS.Runtime/BGCS.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup Label="Generated source inputs">
    <Compile Include="../Generated/**/*.cs" LinkBase="Generated" />
  </ItemGroup>
</Project>
