<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Compilation">
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup Label="Project dependencies">
    <ProjectReference Include="../../../src/BGCS.Core/BGCS.Core.csproj" />
  </ItemGroup>
</Project>
