namespace BGCS.Emission;

using System.Text;
using BGCS.Core.CSharp;
using BGCS.Intermediate;

/// <summary>
/// Emits the ABI-level C# surface from shared binding IR.
/// </summary>
public sealed class CSharpEmitter : IBindingEmitter
{
    public string Name => "C# ABI emitter";

    public IReadOnlyList<string> Emit(BindingModule module, EmissionContext context)
    {
        ArgumentNullException.ThrowIfNull(module);
        ArgumentNullException.ThrowIfNull(context);
        IReadOnlyList<BindingDiagnostic> diagnostics = Validate(module);
        if (diagnostics.Count > 0)
            throw new BindingEmissionException(diagnostics);
        string outputFile = Path.Combine(context.OutputPath, context.SingleFileName);
        Directory.CreateDirectory(context.OutputPath);
        StringBuilder writer = new();
        writer.AppendLine("// <auto-generated/>");
        writer.AppendLine("#nullable enable");
        writer.AppendLine("using System;");
        writer.AppendLine("using System.Diagnostics;");
        writer.AppendLine("using System.Runtime.CompilerServices;");
        writer.AppendLine("using System.Runtime.InteropServices;");
        writer.Append("using ").Append(context.RuntimeNamespace).AppendLine(";");
        writer.AppendLine();
        writer.Append("namespace ").AppendLine(module.Namespace);
        writer.AppendLine("{");
        EmitAliases(writer, module);
        HashSet<string> emittedTypes = new(StringComparer.Ordinal);
        foreach (BindingType type in module.Types.Where(type => type.Kind != BindingTypeKind.Alias))
        {
            if (!emittedTypes.Add(type.ManagedName))
                continue;
            EmitType(writer, type);
        }
        EmitDelegates(writer, module);
        EmitConstants(writer, module);
        EmitFunctions(writer, module);
        EmitFunctionTable(writer, module);
        writer.AppendLine("}");
        File.WriteAllText(outputFile, writer.ToString());
        return [outputFile];
    }

    /// <summary>
    /// Validates that this IR-native emitter can preserve every declaration in a module.
    /// </summary>
    /// <remarks>
    /// Unsupported declarations are errors. Callers can inspect these diagnostics before choosing an emitter;
    /// <see cref="Emit"/> performs the same validation before creating its output directory.
    /// </remarks>
    public IReadOnlyList<BindingDiagnostic> Validate(BindingModule module)
    {
        ArgumentNullException.ThrowIfNull(module);
        List<BindingDiagnostic> diagnostics = [];
        HashSet<string> opaqueStorageTypes = EnumerateTypes(module.Types)
            .Where(type => type.IsOpaqueStorage)
            .Select(type => type.ManagedName)
            .ToHashSet(StringComparer.Ordinal);
        Dictionary<string, string> aliases = module.Types
            .Where(type => type.Kind == BindingTypeKind.Alias && type.UnderlyingType != null)
            .GroupBy(type => type.ManagedName, StringComparer.Ordinal)
            .ToDictionary(group => group.Key, group => group.First().UnderlyingType!.ManagedName, StringComparer.Ordinal);
        foreach (BindingType type in module.Types)
        {
            if (type.Kind is BindingTypeKind.FunctionPointer or BindingTypeKind.Unexposed)
            {
                AddUnsupported(diagnostics,
                    $"Type '{type.NativeName}' has kind '{type.Kind}', which the IR-native C# emitter cannot preserve yet.");
            }
            if (type.Kind == BindingTypeKind.Alias && type.UnderlyingType == null)
            {
                AddUnsupported(diagnostics,
                    $"Alias '{type.NativeName}' does not identify its underlying type.");
            }
            foreach (BindingField field in type.Fields.Where(field => field.IsBitField && field.BitWidth > 0))
            {
                int storageBits = field.Type.Size * 8;
                if (field.Type.Size is not (1 or 2 or 4 or 8) || field.BitWidth > storageBits)
                {
                    AddUnsupported(diagnostics,
                        $"Field '{type.NativeName}.{field.NativeName}' is a {field.BitWidth}-bit bitfield with unsupported {field.Type.Size}-byte storage.");
                }
            }
        }
        foreach (BindingFunction function in module.Functions)
        {
            if (function.Kind != BindingFunctionKind.Free)
            {
                AddUnsupported(diagnostics,
                    $"Callable '{function.NativeName}' has kind '{function.Kind}'; only free C ABI functions are supported by this emitter.");
            }
            if (function.IsVariadic)
            {
                AddUnsupported(diagnostics,
                    $"Function '{function.NativeName}' is variadic and requires explicitly configured fixed signatures.");
            }
            ValidateOpaqueByValue(diagnostics, opaqueStorageTypes, aliases, function.ReturnType,
                $"return type of function '{function.NativeName}'");
            foreach (BindingParameter parameter in function.Parameters)
            {
                ValidateOpaqueByValue(diagnostics, opaqueStorageTypes, aliases, parameter.Type,
                    $"parameter '{parameter.NativeName}' of function '{function.NativeName}'");
            }
            if (module.ImportMode == BindingImportMode.FunctionTable && function.FunctionTableIndex == null)
            {
                AddUnsupported(diagnostics,
                    $"Function-table callable '{function.NativeName}' does not have an assigned slot.");
            }
            if (module.ImportMode == BindingImportMode.FunctionTable && function.FunctionTableIndex is int index &&
                !module.FunctionTableEntries.Any(entry => entry.Index == index &&
                    string.Equals(entry.EntryPoint, function.NativeName, StringComparison.Ordinal)))
            {
                AddUnsupported(diagnostics,
                    $"Function-table callable '{function.NativeName}' has slot {index}, but the module does not define the matching entry point.");
            }
        }
        foreach (BindingDelegate bindingDelegate in module.Delegates)
        {
            ValidateOpaqueByValue(diagnostics, opaqueStorageTypes, aliases, bindingDelegate.ReturnType,
                $"return type of delegate '{bindingDelegate.NativeName}'");
            foreach (BindingParameter parameter in bindingDelegate.Parameters)
            {
                ValidateOpaqueByValue(diagnostics, opaqueStorageTypes, aliases, parameter.Type,
                    $"parameter '{parameter.NativeName}' of delegate '{bindingDelegate.NativeName}'");
            }
        }
        if (module.ImportMode == BindingImportMode.FunctionTable)
        {
            foreach (IGrouping<int, BindingFunctionTableEntry> duplicate in module.FunctionTableEntries.GroupBy(entry => entry.Index)
                         .Where(group => group.Count() > 1))
            {
                AddUnsupported(diagnostics, $"Function-table slot {duplicate.Key} is assigned more than once.");
            }
        }
        return diagnostics.AsReadOnly();
    }

    private static IEnumerable<BindingType> EnumerateTypes(IEnumerable<BindingType> types)
    {
        foreach (BindingType type in types)
        {
            yield return type;
            foreach (BindingType nested in EnumerateTypes(type.NestedTypes))
                yield return nested;
        }
    }

    private static void ValidateOpaqueByValue(ICollection<BindingDiagnostic> diagnostics,
        ISet<string> opaqueStorageTypes, IReadOnlyDictionary<string, string> aliases,
        BindingTypeReference reference, string location)
    {
        if (reference.PointerDepth > 0 || reference.ManagedName.Contains('*'))
            return;
        string managedName = reference.ManagedName;
        HashSet<string> visited = new(StringComparer.Ordinal);
        while (visited.Add(managedName) && aliases.TryGetValue(managedName, out string? target))
            managedName = target;
        if (opaqueStorageTypes.Contains(managedName))
        {
            AddUnsupported(diagnostics,
                $"The {location} uses opaque storage type '{managedName}' by value; expose its native definition or use a pointer so ABI classification is unambiguous.");
        }
    }

    private static void EmitAliases(StringBuilder writer, BindingModule module)
    {
        HashSet<string> concreteTypes = module.Types
            .Where(type => type.Kind != BindingTypeKind.Alias)
            .Select(type => type.ManagedName)
            .ToHashSet(StringComparer.Ordinal);
        foreach (BindingType type in module.Types.Where(type => type.Kind == BindingTypeKind.Alias && type.UnderlyingType != null))
        {
            if (CsType.IsKnownPrimitive(type.ManagedName))
                continue;
            string target = type.UnderlyingType!.ManagedName.Contains('*')
                ? "nint"
                : type.UnderlyingType.ManagedName;
            if (concreteTypes.Contains(type.ManagedName))
                continue;
            if (!CsType.IsKnownPrimitive(target) && concreteTypes.Contains(target))
                target = $"global::{module.Namespace}.{target}";
            if (!string.Equals(type.ManagedName, target, StringComparison.Ordinal))
                writer.Append("    using ").Append(type.ManagedName).Append(" = ").Append(target).AppendLine(";");
        }
        if (module.Types.Any(type => type.Kind == BindingTypeKind.Alias && type.UnderlyingType != null))
            writer.AppendLine();
    }

    private static void EmitDelegates(StringBuilder writer, BindingModule module)
    {
        foreach (BindingDelegate bindingDelegate in module.Delegates)
        {
            writer.Append("    [UnmanagedFunctionPointer(CallingConvention.")
                .Append(GetCallingConvention(bindingDelegate.CallingConvention)).AppendLine(")] ");
            writer.Append("    public unsafe delegate ").Append(bindingDelegate.ReturnType.ManagedName).Append(' ')
                .Append(bindingDelegate.ManagedName).Append('(');
            EmitParameters(writer, bindingDelegate.Parameters);
            writer.AppendLine(");");
            writer.AppendLine();
        }
    }

    private static void EmitConstants(StringBuilder writer, BindingModule module)
    {
        if (module.Constants.Count == 0)
            return;
        writer.Append("    public static unsafe partial class ").AppendLine(module.Name);
        writer.AppendLine("    {");
        foreach (BindingConstant constant in module.Constants)
            writer.Append("        public const ").Append(constant.ManagedType).Append(' ')
                .Append(constant.ManagedName).Append(" = ").Append(constant.Value).AppendLine(";");
        writer.AppendLine("    }");
        writer.AppendLine();
    }

    private static void AddUnsupported(ICollection<BindingDiagnostic> diagnostics, string message)
    {
        diagnostics.Add(new BindingDiagnostic(
            BindingDiagnosticSeverity.Error,
            message,
            BindingDiagnosticCodes.CSharpUnsupported));
    }

    private static void EmitType(StringBuilder writer, BindingType type)
    {
        switch (type.Kind)
        {
            case BindingTypeKind.Enumeration:
                string underlying = type.UnderlyingType?.ManagedName ?? (type.Size > 4 ? "long" : "int");
                writer.Append("    public enum ").Append(type.ManagedName).Append(" : ").AppendLine(underlying);
                writer.AppendLine("    {");
                foreach (BindingEnumMember item in type.EnumMembers)
                    writer.Append("        ").Append(item.ManagedName).Append(" = ").Append(item.Value).AppendLine(",");
                writer.AppendLine("    }");
                writer.AppendLine();
                break;
            case BindingTypeKind.Structure:
            case BindingTypeKind.Union:
                bool explicitLayout = type.Kind == BindingTypeKind.Union || type.Fields.Any(field => field.IsBitField);
                bool opaqueStorage = type.NestedTypes.Count == 0 && type.Fields.Count == 0;
                writer.Append("    [StructLayout(LayoutKind.")
                    .Append(explicitLayout ? "Explicit" : "Sequential");
                if ((explicitLayout || opaqueStorage) && type.Size > 0)
                    writer.Append(", Size = ").Append(type.Size);
                if (opaqueStorage && type.Size > 0 && type.Alignment is 1 or 2 or 4 or 8)
                    writer.Append(", Pack = ").Append(type.Alignment);
                writer.AppendLine(")] ");
                writer.Append("    public unsafe partial struct ").AppendLine(type.ManagedName);
                writer.AppendLine("    {");
                foreach (BindingType nestedType in type.NestedTypes)
                {
                    StringBuilder nestedWriter = new();
                    EmitType(nestedWriter, nestedType);
                    AppendIndented(writer, nestedWriter, "    ");
                }
                if (type.NestedTypes.Count == 0 && type.Fields.Count == 0)
                {
                    writer.AppendLine("#pragma warning disable CS0169");
                    if (explicitLayout)
                        writer.AppendLine("        [FieldOffset(0)]");
                    writer.Append("        private ").Append(GetAlignmentStorageType(type.Alignment)).AppendLine(" _opaque;");
                    writer.AppendLine("#pragma warning restore CS0169");
                }
                int bitfieldIndex = 0;
                for (int fieldIndex = 0; fieldIndex < type.Fields.Count; fieldIndex++)
                {
                    BindingField field = type.Fields[fieldIndex];
                    if (!field.IsBitField)
                    {
                        EmitField(writer, field, explicitLayout);
                        continue;
                    }
                    if (field.BitWidth <= 0)
                        continue;
                    fieldIndex = EmitBitfieldGroup(writer, type.Fields, fieldIndex, bitfieldIndex++);
                }
                writer.AppendLine("    }");
                writer.AppendLine();
                break;
            case BindingTypeKind.OpaqueHandle:
                writer.AppendLine("    [DebuggerDisplay(\"{DebuggerDisplay,nq}\")] ");
                writer.Append("    public readonly partial struct ").Append(type.ManagedName).AppendLine(" : IEquatable<" + type.ManagedName + ">");
                writer.AppendLine("    {");
                writer.Append("        public ").Append(type.ManagedName).AppendLine("(nint handle) { Handle = handle; }");
                writer.AppendLine("        public nint Handle { get; }");
                writer.AppendLine("        public bool IsNull => Handle == 0;");
                writer.Append("        public static ").Append(type.ManagedName).Append(" Null => new ")
                    .Append(type.ManagedName).AppendLine("(0);");
                writer.Append("        public static implicit operator ").Append(type.ManagedName)
                    .Append("(nint handle) => new ").Append(type.ManagedName).AppendLine("(handle);");
                writer.Append("        public static bool operator ==(").Append(type.ManagedName).Append(" left, ")
                    .Append(type.ManagedName).AppendLine(" right) => left.Handle == right.Handle;");
                writer.Append("        public static bool operator !=(").Append(type.ManagedName).Append(" left, ")
                    .Append(type.ManagedName).AppendLine(" right) => left.Handle != right.Handle;");
                writer.Append("        public bool Equals(").Append(type.ManagedName).AppendLine(" other) => Handle == other.Handle;");
                writer.AppendLine("        public override bool Equals(object? obj) => obj is " + type.ManagedName + " other && Equals(other);");
                writer.AppendLine("        public override int GetHashCode() => Handle.GetHashCode();");
                writer.Append("        private string DebuggerDisplay => string.Format(\"").Append(type.ManagedName)
                    .AppendLine(" [0x{0}]\", Handle.ToString(\"X\"));");
                writer.AppendLine("    }");
                writer.AppendLine();
                break;
        }
    }

    private static void AppendIndented(StringBuilder writer, StringBuilder content, string indent)
    {
        using StringReader reader = new(content.ToString());
        while (reader.ReadLine() is { } line)
        {
            if (line.Length > 0)
                writer.Append(indent);
            writer.AppendLine(line);
        }
    }

    private static string GetAlignmentStorageType(int alignment)
    {
        return alignment switch
        {
            2 => "ushort",
            4 => "uint",
            8 => "ulong",
            _ => "byte"
        };
    }

    private static int EmitBitfieldGroup(StringBuilder writer, IList<BindingField> fields, int startIndex,
        int storageIndex)
    {
        BindingField first = fields[startIndex];
        int storageBits = first.Type.Size * 8;
        string storageName = $"RawBits{storageIndex}";
        writer.Append("        [FieldOffset(").Append(first.Offset).AppendLine(")] ");
        writer.Append("        public ").Append(first.Type.ManagedName).Append(' ').Append(storageName).AppendLine(";");
        int lastIndex = startIndex;
        for (int index = startIndex; index < fields.Count; index++)
        {
            BindingField field = fields[index];
            long relativeBitOffset = field.BitOffset - first.BitOffset;
            if (!field.IsBitField || field.BitWidth <= 0 ||
                !string.Equals(field.Type.NativeName, first.Type.NativeName, StringComparison.Ordinal) ||
                relativeBitOffset < 0 || relativeBitOffset + field.BitWidth > storageBits)
                break;
            writer.Append("        public ").Append(field.Type.ManagedName).Append(' ').Append(field.ManagedName)
                .Append(" { get => ");
            if (field.IsSignedBitField)
                writer.Append("Bitfield.GetSigned(").Append(storageName).Append(", ").Append(relativeBitOffset)
                    .Append(", ").Append(field.BitWidth).Append(')');
            else
                writer.Append("Bitfield.Get(").Append(storageName).Append(", ").Append(relativeBitOffset)
                    .Append(", ").Append(field.BitWidth).Append(')');
            writer.Append("; set => Bitfield.Set(ref ").Append(storageName).Append(", value, ")
                .Append(relativeBitOffset).Append(", ").Append(field.BitWidth).AppendLine("); }");
            lastIndex = index;
        }
        return lastIndex;
    }

    private static void EmitField(StringBuilder writer, BindingField field, bool union)
    {
        int count = field.ArrayDimensions.Count == 0 ? 1 : field.ArrayDimensions.Aggregate(1, (value, dimension) => dimension <= 0 ? 0 : checked(value * dimension));
        if (count == 0)
        {
            writer.Append("        public const int ").Append(field.ManagedName).Append("Offset = ").Append(field.Offset).AppendLine(";");
            return;
        }
        for (int i = 0; i < count; i++)
        {
            if (union)
                writer.Append("        [FieldOffset(").Append(field.Offset + i * field.Type.Size).AppendLine(")] ");
            writer.Append("        public ").Append(field.Type.ManagedName).Append(' ').Append(field.ManagedName);
            if (count > 1)
                writer.Append('_').Append(i);
            writer.AppendLine(";");
        }
    }

    private static void EmitFunctions(StringBuilder writer, BindingModule module)
    {
        if (module.Functions.Count == 0)
            return;
        writer.Append("    public static unsafe partial class ").AppendLine(module.Name);
        writer.AppendLine("    {");
        foreach (BindingFunction function in module.Functions.Where(function => function.Kind == BindingFunctionKind.Free))
        {
            switch (module.ImportMode)
            {
                case BindingImportMode.DllImport:
                    writer.Append("        [DllImport(\"").Append(module.LibraryName).Append("\", EntryPoint = \"")
                        .Append(function.NativeName).Append("\", CallingConvention = CallingConvention.")
                        .Append(GetCallingConvention(function.CallingConvention)).AppendLine(")] ");
                    EmitExternFunction(writer, function, "internal static extern");
                    break;
                case BindingImportMode.LibraryImport:
                    writer.Append("        [LibraryImport(\"").Append(module.LibraryName).Append("\", EntryPoint = \"")
                        .Append(function.NativeName).AppendLine("\")] ");
                    writer.Append("        [UnmanagedCallConv(CallConvs = new Type[] { typeof(CallConv")
                        .Append(GetUnmanagedCallingConvention(function.CallingConvention)).AppendLine(") })] ");
                    EmitExternFunction(writer, function, "internal static partial");
                    break;
                case BindingImportMode.FunctionTable:
                    EmitFunctionTableCall(writer, function);
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(module.ImportMode), module.ImportMode, null);
            }
        }
        writer.AppendLine("    }");
    }

    private static void EmitExternFunction(StringBuilder writer, BindingFunction function, string modifiers)
    {
        writer.Append("        ").Append(modifiers).Append(' ').Append(function.ReturnType.ManagedName).Append(' ')
            .Append(function.ManagedName).Append("Native(");
        EmitParameters(writer, function.Parameters);
        writer.AppendLine(");");
    }

    private static void EmitFunctionTableCall(StringBuilder writer, BindingFunction function)
    {
        int tableIndex = function.FunctionTableIndex.GetValueOrDefault();
        writer.Append("        internal static ").Append(function.ReturnType.ManagedName).Append(' ')
            .Append(function.ManagedName).Append("Native(");
        EmitParameters(writer, function.Parameters);
        writer.AppendLine(")");
        writer.AppendLine("        {");
        writer.Append("            ");
        if (!string.Equals(function.ReturnType.ManagedName, "void", StringComparison.Ordinal))
            writer.Append("return ");
        writer.Append("((delegate* unmanaged[").Append(GetUnmanagedCallingConvention(function.CallingConvention)).Append("]<");
        foreach (BindingParameter parameter in function.Parameters)
            writer.Append(parameter.Type.ManagedName).Append(", ");
        writer.Append(function.ReturnType.ManagedName).Append(">)funcTable[").Append(tableIndex)
            .Append("])(");
        for (int index = 0; index < function.Parameters.Count; index++)
        {
            if (index > 0)
                writer.Append(", ");
            writer.Append(function.Parameters[index].ManagedName);
        }
        writer.AppendLine(");");
        writer.AppendLine("        }");
    }

    private static void EmitFunctionTable(StringBuilder writer, BindingModule module)
    {
        if (module.ImportMode != BindingImportMode.FunctionTable || module.FunctionTableEntries.Count == 0)
            return;
        int tableSize = module.FunctionTableEntries.Max(entry => entry.Index) + 1;
        writer.Append("    public static unsafe partial class ").AppendLine(module.Name);
        writer.AppendLine("    {");
        writer.AppendLine("        internal static FunctionTable funcTable;");
        writer.AppendLine();
        if (module.UseCustomContext)
        {
            writer.AppendLine("        public static void InitApi(INativeContext context)");
            writer.AppendLine("        {");
            writer.Append("            funcTable = new FunctionTable(context, ").Append(tableSize).AppendLine(");");
            EmitFunctionTableLoads(writer, module);
            writer.AppendLine("        }");
        }
        else
        {
            if (string.Equals(module.GetLibraryNameFunctionName, "GetLibraryName", StringComparison.Ordinal))
            {
                writer.Append("        private static string GetLibraryName() => \"")
                    .Append(EscapeString(module.LibraryName)).AppendLine("\";");
                writer.AppendLine();
            }
            writer.AppendLine("        public static void InitApi()");
            writer.AppendLine("        {");
            writer.Append("            funcTable = new FunctionTable(LibraryLoader.LoadLibrary(")
                .Append(module.GetLibraryNameFunctionName).Append(", ")
                .Append(module.GetLibraryExtensionFunctionName ?? "null").Append("), ").Append(tableSize).AppendLine(");");
            EmitFunctionTableLoads(writer, module);
            writer.AppendLine("        }");
        }
        writer.AppendLine();
        writer.AppendLine("        public static void FreeApi() => funcTable.Free();");
        writer.AppendLine("    }");
    }

    private static void EmitFunctionTableLoads(StringBuilder writer, BindingModule module)
    {
        foreach (BindingFunctionTableEntry entry in module.FunctionTableEntries.OrderBy(entry => entry.Index))
            writer.Append("            funcTable.Load(").Append(entry.Index).Append(", \"")
                .Append(EscapeString(entry.EntryPoint)).AppendLine("\");");
    }

    private static string EscapeString(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal);

    private static void EmitParameters(StringBuilder writer, IList<BindingParameter> parameters)
    {
        for (int i = 0; i < parameters.Count; i++)
            EmitParameter(writer, parameters[i], i > 0);
    }

    private static void EmitParameter(StringBuilder writer, BindingParameter parameter, bool prefixComma)
    {
        if (prefixComma)
            writer.Append(", ");
        writer.Append(parameter.Type.ManagedName).Append(' ').Append(parameter.ManagedName);
    }

    private static string GetCallingConvention(string value)
    {
        return value switch
        {
            "X86StdCall" => "StdCall",
            "X86ThisCall" => "ThisCall",
            "X86FastCall" => "FastCall",
            _ => "Cdecl"
        };
    }

    private static string GetUnmanagedCallingConvention(string value)
    {
        return value switch
        {
            "X86StdCall" => "Stdcall",
            "X86ThisCall" => "Thiscall",
            "X86FastCall" => "Fastcall",
            _ => "Cdecl"
        };
    }
}
