namespace BGCS.Emission;

using System.Text;
using BGCS.Intermediate;

/// <summary>
/// Emits the ABI-level C# surface from shared binding IR.
/// </summary>
public sealed class CSharpEmitter : IBindingEmitter
{
    public string Name => "C# ABI emitter";

    public IReadOnlyList<string> Emit(BindingModule module, EmissionContext context)
    {
        ArgumentNullException.ThrowIfNull(module);
        ArgumentNullException.ThrowIfNull(context);
        IReadOnlyList<BindingDiagnostic> diagnostics = Validate(module);
        if (diagnostics.Count > 0)
            throw new BindingEmissionException(diagnostics);
        string outputFile = Path.Combine(context.OutputPath, context.SingleFileName);
        Directory.CreateDirectory(context.OutputPath);
        StringBuilder writer = new();
        writer.AppendLine("// <auto-generated/>");
        writer.AppendLine("using System;");
        writer.AppendLine("using System.Runtime.InteropServices;");
        writer.AppendLine("using BGCS.Runtime;");
        writer.AppendLine();
        writer.Append("namespace ").AppendLine(module.Namespace);
        writer.AppendLine("{");
        HashSet<string> emittedTypes = new(StringComparer.Ordinal);
        foreach (BindingType type in module.Types)
        {
            if (!emittedTypes.Add(type.ManagedName))
                continue;
            EmitType(writer, type);
        }
        EmitFunctions(writer, module);
        writer.AppendLine("}");
        File.WriteAllText(outputFile, writer.ToString());
        return [outputFile];
    }

    /// <summary>
    /// Validates that this IR-native emitter can preserve every declaration in a module.
    /// </summary>
    /// <remarks>
    /// Unsupported declarations are errors. Callers can inspect these diagnostics before choosing an emitter;
    /// <see cref="Emit"/> performs the same validation before creating its output directory.
    /// </remarks>
    public IReadOnlyList<BindingDiagnostic> Validate(BindingModule module)
    {
        ArgumentNullException.ThrowIfNull(module);
        List<BindingDiagnostic> diagnostics = [];
        foreach (BindingType type in module.Types)
        {
            if (type.Kind is BindingTypeKind.FunctionPointer or BindingTypeKind.Unexposed)
            {
                AddUnsupported(diagnostics,
                    $"Type '{type.NativeName}' has kind '{type.Kind}', which the IR-native C# emitter cannot preserve yet.");
            }
            foreach (BindingField field in type.Fields.Where(field => field.BitWidth > 0))
            {
                AddUnsupported(diagnostics,
                    $"Field '{type.NativeName}.{field.NativeName}' is a {field.BitWidth}-bit bitfield, which requires an explicit storage and accessor lowering.");
            }
        }
        foreach (BindingFunction function in module.Functions)
        {
            if (function.Kind != BindingFunctionKind.Free)
            {
                AddUnsupported(diagnostics,
                    $"Callable '{function.NativeName}' has kind '{function.Kind}'; only free C ABI functions are supported by this emitter.");
            }
            if (function.IsVariadic)
            {
                AddUnsupported(diagnostics,
                    $"Function '{function.NativeName}' is variadic and requires explicitly configured fixed signatures.");
            }
        }
        return diagnostics.AsReadOnly();
    }

    private static void AddUnsupported(ICollection<BindingDiagnostic> diagnostics, string message)
    {
        diagnostics.Add(new BindingDiagnostic(
            BindingDiagnosticSeverity.Error,
            message,
            BindingDiagnosticCodes.CSharpUnsupported));
    }

    private static void EmitType(StringBuilder writer, BindingType type)
    {
        switch (type.Kind)
        {
            case BindingTypeKind.Enumeration:
                string underlying = type.Size > 4 ? "long" : "int";
                writer.Append("    public enum ").Append(type.ManagedName).Append(" : ").AppendLine(underlying);
                writer.AppendLine("    {");
                foreach (BindingEnumMember item in type.EnumMembers)
                    writer.Append("        ").Append(item.ManagedName).Append(" = ").Append(item.Value).AppendLine(",");
                writer.AppendLine("    }");
                writer.AppendLine();
                break;
            case BindingTypeKind.Structure:
            case BindingTypeKind.Union:
                writer.Append("    [StructLayout(LayoutKind.")
                    .Append(type.Kind == BindingTypeKind.Union ? "Explicit" : "Sequential").AppendLine(")] ");
                writer.Append("    public unsafe partial struct ").AppendLine(type.ManagedName);
                writer.AppendLine("    {");
                foreach (BindingField field in type.Fields)
                    EmitField(writer, field, type.Kind == BindingTypeKind.Union);
                writer.AppendLine("    }");
                writer.AppendLine();
                break;
            case BindingTypeKind.OpaqueHandle:
                writer.Append("    public readonly partial struct ").Append(type.ManagedName).AppendLine(" : IEquatable<" + type.ManagedName + ">");
                writer.AppendLine("    {");
                writer.AppendLine("        public readonly nint Handle;");
                writer.Append("        public ").Append(type.ManagedName).AppendLine("(nint handle) => Handle = handle;");
                writer.Append("        public bool Equals(").Append(type.ManagedName).AppendLine(" other) => Handle == other.Handle;");
                writer.AppendLine("        public override bool Equals(object? obj) => obj is " + type.ManagedName + " other && Equals(other);");
                writer.AppendLine("        public override int GetHashCode() => Handle.GetHashCode();");
                writer.AppendLine("    }");
                writer.AppendLine();
                break;
        }
    }

    private static void EmitField(StringBuilder writer, BindingField field, bool union)
    {
        int count = field.ArrayDimensions.Count == 0 ? 1 : field.ArrayDimensions.Aggregate(1, (value, dimension) => dimension <= 0 ? 0 : checked(value * dimension));
        if (count == 0)
        {
            writer.Append("        public const int ").Append(field.ManagedName).Append("Offset = ").Append(field.Offset).AppendLine(";");
            return;
        }
        for (int i = 0; i < count; i++)
        {
            if (union)
                writer.Append("        [FieldOffset(").Append(field.Offset + i * field.Type.Size).AppendLine(")] ");
            writer.Append("        public ").Append(field.Type.ManagedName).Append(' ').Append(field.ManagedName);
            if (count > 1)
                writer.Append('_').Append(i);
            writer.AppendLine(";");
        }
    }

    private static void EmitFunctions(StringBuilder writer, BindingModule module)
    {
        if (module.Functions.Count == 0)
            return;
        writer.Append("    public static unsafe partial class ").AppendLine(module.Name);
        writer.AppendLine("    {");
        foreach (BindingFunction function in module.Functions.Where(function => function.Kind == BindingFunctionKind.Free))
        {
            writer.Append("        [DllImport(\"").Append(module.LibraryName).Append("\", EntryPoint = \"")
                .Append(function.NativeName).Append("\", CallingConvention = CallingConvention.")
                .Append(GetCallingConvention(function.CallingConvention)).AppendLine(")] ");
            writer.Append("        internal static extern ").Append(function.ReturnType.ManagedName).Append(' ')
                .Append(function.ManagedName).Append("Native(");
            for (int i = 0; i < function.Parameters.Count; i++)
            {
                if (i > 0)
                    writer.Append(", ");
                BindingParameter parameter = function.Parameters[i];
                writer.Append(parameter.Type.ManagedName).Append(' ').Append(parameter.ManagedName);
            }
            writer.AppendLine(");");
        }
        writer.AppendLine("    }");
    }

    private static string GetCallingConvention(string value)
    {
        return value switch
        {
            "X86StdCall" => "StdCall",
            "X86ThisCall" => "ThisCall",
            "X86FastCall" => "FastCall",
            _ => "Cdecl"
        };
    }
}
