namespace BGCS.Emission;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

/// <summary>
/// Composes generated C# syntax trees into one deterministic compilation unit.
/// </summary>
public sealed class SingleFileComposer
{
    private const string Header = """
        // ------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by BindGen-CS.
        //     Changes will be replaced the next time bindings are generated.
        // </auto-generated>
        // ------------------------------------------------------------------------------

        """;

    public string Compose(IEnumerable<string> sourceFiles, string outputFile, string targetNamespace)
    {
        ArgumentNullException.ThrowIfNull(sourceFiles);
        if (string.IsNullOrWhiteSpace(outputFile))
            throw new ArgumentException("An output file is required.", nameof(outputFile));
        if (string.IsNullOrWhiteSpace(targetNamespace))
            throw new ArgumentException("A target namespace is required.", nameof(targetNamespace));

        return ComposeSources(sourceFiles.Select(path => (Path: path, Text: File.ReadAllText(path))), outputFile, targetNamespace);
    }

    public string ComposeSources(IEnumerable<(string Path, string Text)> sources, string outputFile, string targetNamespace)
    {
        ArgumentNullException.ThrowIfNull(sources);
        Dictionary<string, UsingDirectiveSyntax> usings = new(StringComparer.Ordinal);
        Dictionary<string, UsingDirectiveSyntax> namespaceUsings = new(StringComparer.Ordinal);
        List<AttributeListSyntax> attributes = [];
        List<MemberDeclarationSyntax> namespaceMembers = [];
        List<MemberDeclarationSyntax> otherMembers = [];
        foreach ((string sourceFile, string sourceText) in sources.OrderBy(source => source.Path, StringComparer.OrdinalIgnoreCase))
        {
            SyntaxTree tree = CSharpSyntaxTree.ParseText(sourceText, path: sourceFile);
            Diagnostic[] errors = tree.GetDiagnostics().Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error).ToArray();
            if (errors.Length > 0)
                throw new InvalidOperationException($"Cannot compose invalid generated source '{sourceFile}':{Environment.NewLine}{string.Join(Environment.NewLine, errors.Select(error => error.ToString()))}");
            CompilationUnitSyntax root = tree.GetCompilationUnitRoot();
            foreach (UsingDirectiveSyntax directive in root.Usings)
                usings.TryAdd(directive.WithoutTrivia().ToFullString(), directive.WithoutTrivia());
            attributes.AddRange(root.AttributeLists.Select(attribute => attribute.WithoutTrivia()));
            foreach (MemberDeclarationSyntax member in root.Members)
            {
                if (member is BaseNamespaceDeclarationSyntax ns && ns.Name.ToString() == targetNamespace)
                {
                    foreach (UsingDirectiveSyntax directive in ns.Usings)
                    {
                        UsingDirectiveSyntax normalizedDirective = directive.WithoutTrivia();
                        Dictionary<string, UsingDirectiveSyntax> target = directive.Alias == null ? usings : namespaceUsings;
                        target.TryAdd(normalizedDirective.ToFullString(), normalizedDirective);
                    }
                    namespaceMembers.AddRange(ns.Members);
                }
                else
                {
                    otherMembers.Add(member);
                }
            }
        }

        CompilationUnitSyntax output = SyntaxFactory.CompilationUnit()
            .WithAttributeLists(SyntaxFactory.List(attributes))
            .WithUsings(SyntaxFactory.List(usings.OrderBy(pair => pair.Key, StringComparer.Ordinal).Select(pair => pair.Value)));
        List<MemberDeclarationSyntax> members = [];
        if (namespaceMembers.Count > 0)
        {
            members.Add(SyntaxFactory.NamespaceDeclaration(SyntaxFactory.ParseName(targetNamespace))
                .WithUsings(SyntaxFactory.List(namespaceUsings.OrderBy(pair => pair.Key, StringComparer.Ordinal).Select(pair => pair.Value)))
                .WithMembers(SyntaxFactory.List(namespaceMembers)));
        }
        members.AddRange(otherMembers);
        output = output.WithMembers(SyntaxFactory.List(members));
        string normalized = output.NormalizeWhitespace("    ", Environment.NewLine).ToFullString()
            .Replace("> )", ">)", StringComparison.Ordinal);
        string text = Header + normalized + Environment.NewLine;
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputFile))!);
        File.WriteAllText(outputFile, text);
        return outputFile;
    }
}
