using BGCS.Core.Collections;

namespace BGCS.GenerationSteps
{
    using BGCS.Core;
    using BGCS.CppAst.Model.Declarations;
    using BGCS.CppAst.Model.Types;
    using BGCS.Metadata;
    using System.Collections.Generic;
    using System.IO;

    /// <summary>
    /// Generates C# alias declarations for non-handle typedefs (e.g. using MyInt = int;).
    /// </summary>
    public class TypedefAliasGenerationStep : GenerationStep
    {
        private readonly HashSet<string> libDefinedTypedefs = [];
        private readonly HashSet<string> definedTypedefs = [];

        public TypedefAliasGenerationStep(CsCodeGenerator generator, CsCodeGeneratorConfig config) : base(generator, config)
        {
        }

        public override string Name { get; } = "TypedefAliases";

        public override void Configure(CsCodeGeneratorConfig config)
        {
            // Alias generation is only needed when typedef squash is disabled.
            Enabled = !config.AutoSquashTypedef;
        }

        public override void CopyToMetadata(CsCodeGeneratorMetadata metadata)
        {
            metadata.DefinedTypedefs.AddRange(definedTypedefs);
        }

        public override void CopyFromMetadata(CsCodeGeneratorMetadata metadata)
        {
            libDefinedTypedefs.AddRange(metadata.DefinedTypedefs);
        }

        public override void Reset()
        {
            libDefinedTypedefs.Clear();
            definedTypedefs.Clear();
        }

        public override void Generate(FileSet files, ParseResult result, string outputPath, CsCodeGeneratorConfig config, CsCodeGeneratorMetadata metadata)
        {
            if (!Enabled)
            {
                return;
            }

            string folder = Path.Combine(outputPath, "Aliases");
            if (Directory.Exists(folder))
            {
                Directory.Delete(folder, true);
            }
            Directory.CreateDirectory(folder);

            string filePath = Path.Combine(folder, "TypedefAliases.cs");
            using var writer = new CsCodeWriter(filePath, config.Namespace, [], config.HeaderInjector);

            foreach (CppTypedef typedef in result.Compilation.Typedefs)
            {
                if (!files.Contains(typedef.SourceFile))
                {
                    continue;
                }

                if (FilterTypedef(typedef))
                {
                    continue;
                }

                string aliasName = config.GetCsCleanName(typedef.Name);
                string targetType = GetAliasTargetTypeName(typedef);

                if (string.IsNullOrWhiteSpace(targetType) || aliasName == targetType)
                {
                    continue;
                }

                writer.WriteLine($"using {aliasName} = {targetType};");
            }
        }

        private bool FilterTypedef(CppTypedef typedef)
        {
            if (config.AllowedTypedefs.Count != 0 && !config.AllowedTypedefs.Contains(typedef.Name))
            {
                return true;
            }
            if (config.IgnoredTypedefs.Contains(typedef.Name))
            {
                return true;
            }

            string aliasName = config.GetCsCleanName(typedef.Name);
            if (libDefinedTypedefs.Contains(aliasName) || definedTypedefs.Contains(aliasName))
            {
                return true;
            }

            // Handles and function pointers are generated by dedicated steps.
            if (typedef.IsOpaqueHandle() || typedef.IsDelegate())
            {
                return true;
            }
            if (typedef.ElementType is CppPointerType pointer && pointer.ElementType is not CppFunctionType)
            {
                return true;
            }

            // Mapped enum typedefs are handled by enum/type conversion.
            if (config.TypedefToEnumMappings.ContainsKey(typedef.Name))
            {
                return true;
            }

            definedTypedefs.Add(aliasName);
            return false;
        }

        private string GetAliasTargetTypeName(CppTypedef typedef)
        {
            CppType current = typedef.ElementType;
            while (current is CppTypedef innerTypedef)
            {
                current = innerTypedef.ElementType;
            }

            return config.GetCsTypeName(current);
        }
    }
}
